# Generated by Django 3.2.15 on 2023-02-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230214_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='location',
        ),
    ]
