# Generated by Django 3.2.15 on 2023-02-14 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230214_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='api.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
